### ISSUE TITLE
Rejected from App Store

### ISSUE THREAD

**Issue by jeef3** [react-native-webrtc/react-native-voip-push-notification#11]
I think it might be worth having a note in the readme that Apple will reject apps using this method if you are only using it for push notifications. That is, you must’ve using voice over IP services if you enable the voip background mode, or your app will get rejected.

**Comment by bsiddiqui** [comment]
@jeef3 that seems unnecessary to mention - voip tokens are meant for voip applications, push tokens are meant for push notifications

**Comment by morksinaanab** [comment]
This is not true in all cases. Our app was rejected twice for integration voip support, in order to use the push notifications. However after I explained why we used the voip push notifications with my next  submission in the explanation field, as well as before i submitted it gave a heads-up with the contact form (We needed it to trigger a video call, and not using it for anything else, like background keep-alive - the silent push notification option just wasn't reliable enough), they have accepted it.
